# Generated by Django 3.0.8 on 2020-08-07 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200807_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affine1', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=1), size=1)),
                ('affine2', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=300), size=6)),
            ],
        ),
        migrations.RenameModel(
            old_name='Wavelet_Class',
            new_name='Wavelet',
        ),
        migrations.DeleteModel(
            name='Weights',
        ),
    ]
