# Generated by Django 3.0.8 on 2020-08-07 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200807_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='affine1',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=5), size=5),
        ),
    ]
